#!/usr/bin/env node
/**
 * build-tokens — kit/tokens/core.css is the single source of truth.
 *
 * Emits JSON / SCSS / TypeScript / DTCG tokens so that consumers in other languages
 * never hand-copy a value out of the CSS (or worse, out of the prose).
 *
 * Also enforces the naming convention at build time rather than at review time:
 * a token whose prefix is not a known group fails the build.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "kit/tokens/generated");

/** Prefixes a token name may legally start with. Extend deliberately. */
const GROUPS = [
  "color", "font", "text", "leading", "tracking", "space", "width", "padding",
  "icon", "radius", "stroke", "duration", "ease", "stagger",
];

/** Strip comments, then read every `--name: value;` declaration in order. */
function parse(css) {
  const clean = css.replace(/\/\*[\s\S]*?\*\//g, "");
  const out = new Map();
  const re = /(--[a-z0-9-]+)\s*:\s*([^;}]+)[;}]/gi;
  let m;
  while ((m = re.exec(clean))) out.set(m[1], m[2].trim().replace(/\s+/g, " "));
  return out;
}

function groupOf(name) {
  const bare = name.replace(/^--/, "");
  return GROUPS.find((g) => bare === g || bare.startsWith(g + "-")) ?? null;
}

const coreCss = readFileSync(join(root, "kit/tokens/core.css"), "utf8");
const darkCss = readFileSync(join(root, "kit/tokens/dark.css"), "utf8");
const core = parse(coreCss);
const dark = parse(darkCss);

// --- enforce the naming convention -----------------------------------------
const bad = [...core.keys()].filter((k) => !groupOf(k));
if (bad.length) {
  console.error("✗ tokens with an unrecognised group prefix:\n");
  for (const b of bad) console.error(`    ${b}`);
  console.error(`\n  Known groups: ${GROUPS.join(", ")}`);
  console.error("  Either rename the token, or add the group to GROUPS in this script");
  console.error("  — deliberately, because the group list is the naming convention.\n");
  process.exit(1);
}

// dark.css may only override names core.css already defines
const orphan = [...dark.keys()].filter((k) => !core.has(k));
if (orphan.length) {
  console.error("✗ dark.css defines tokens that core.css does not:\n");
  for (const o of orphan) console.error(`    ${o}`);
  console.error("\n  Dark mode overrides values; it never introduces new tokens.\n");
  process.exit(1);
}

// --- emit -------------------------------------------------------------------
const nested = {};
for (const [name, value] of core) {
  const g = groupOf(name);
  const key = name.replace(/^--/, "").replace(new RegExp(`^${g}-?`), "") || g;
  (nested[g] ??= {})[key] = dark.has(name)
    ? { light: value, dark: dark.get(name) }
    : value;
}

mkdirSync(OUT, { recursive: true });
const banner = "/* Generated by scripts/build-tokens.mjs — do not edit.\n   Source of truth: kit/tokens/core.css + dark.css */\n";

writeFileSync(join(OUT, "tokens.json"), JSON.stringify(nested, null, 2) + "\n");

writeFileSync(
  join(OUT, "tokens.scss"),
  banner.replace(/^\/\*|\*\/$/g, "//").split("\n").map((l) => (l.trim() ? `// ${l.replace(/^\/\/\s*/, "")}` : "")).join("\n") +
    "\n" +
    [...core].map(([n, v]) => `$wx-${n.slice(2)}: ${v};`).join("\n") +
    "\n"
);

const ident = (n) => n.slice(2).replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
writeFileSync(
  join(OUT, "tokens.ts"),
  banner +
    "export const tokens = {\n" +
    [...core].map(([n, v]) => `  ${ident(n)}: ${JSON.stringify(v)},`).join("\n") +
    "\n} as const;\n\nexport type TokenName = keyof typeof tokens;\n\n" +
    "/** camelCase name -> CSS custom property. Generated, not inferred:\n" +
    "    inverting camelCase breaks on multi-digit names like space32. */\n" +
    "const cssNames: Record<TokenName, string> = {\n" +
    [...core.keys()].map((n) => `  ${ident(n)}: ${JSON.stringify(n)},`).join("\n") +
    "\n};\n\nexport const cssVar = (name: TokenName): string => `var(${cssNames[name]})`;\n"
);

// DTCG is the interoperable exchange format used by design tools. CSS has a
// few values (notably clamp()) that DTCG has no native semantic type for; keep
// those faithfully as strings rather than inventing a misleading dimension.
const DTCG_TYPES = {
  color: "color", font: "fontFamily", text: "dimension", leading: "number",
  tracking: "dimension", space: "dimension", width: "string", padding: "string",
  icon: "dimension", radius: "dimension", stroke: "dimension", duration: "duration",
  ease: "cubicBezier", stagger: "duration",
};
const dtcg = {
  "$schema": "https://design-tokens.github.io/community-group/format/",
  "$description": "Generated from kit/tokens/core.css. Dark overrides are carried in the Wenxin extension.",
};
for (const [name, light] of core) {
  const group = groupOf(name);
  const keys = name.slice(2 + group.length + 1).split("-");
  const leaf = {
    "$type": DTCG_TYPES[group],
    "$value": toDtcgValue(light, DTCG_TYPES[group]),
  };
  if (dark.has(name)) {
    leaf.$extensions = {
      "org.wenxin.mode": { dark: toDtcgValue(dark.get(name), DTCG_TYPES[group]) },
    };
  }
  setPath(dtcg, [group, ...keys], leaf);
}
writeFileSync(join(OUT, "tokens.dtcg.json"), JSON.stringify(dtcg, null, 2) + "\n");

function setPath(target, keys, value) {
  const last = keys.pop();
  let node = target;
  for (const key of keys) node = node[key] ??= {};
  node[last] = value;
}

function toDtcgValue(value, type) {
  if (type === "color") return colorValue(value);
  if (type === "fontFamily") return value.split(",").map((font) => font.trim().replace(/^['\"]|['\"]$/g, ""));
  if (type === "cubicBezier") {
    const match = value.match(/^cubic-bezier\(([^)]+)\)$/);
    return match ? match[1].split(",").map(Number) : value;
  }
  if (["dimension", "duration"].includes(type)) {
    const match = value.match(/^(-?(?:\d+|\d*\.\d+))(px|rem|em|ms)$/);
    return match ? { value: Number(match[1]), unit: match[2] } : value;
  }
  if (type === "number" && /^-?(?:\d+|\d*\.\d+)$/.test(value)) return Number(value);
  return value;
}

function colorValue(value) {
  if (/^#[0-9a-f]{6}$/i.test(value)) {
    return { colorSpace: "srgb", components: [1, 3, 5].map((i) => Number.parseInt(value.slice(i, i + 2), 16) / 255), "alpha": 1 };
  }
  const match = value.match(/^rgb\(\s*(\d+)\s+(\d+)\s+(\d+)\s*\/\s*([\d.]+)\s*\)$/i);
  return match
    ? { colorSpace: "srgb", components: match.slice(1, 4).map((channel) => Number(channel) / 255), alpha: Number(match[4]) }
    : value;
}

console.log(`✓ ${core.size} tokens → generated/{tokens.json,tokens.scss,tokens.ts,tokens.dtcg.json}`);
console.log(`  ${dark.size} of them have dark-mode overrides`);
for (const g of GROUPS) {
  const n = Object.keys(nested[g] ?? {}).length;
  if (n) process.stdout.write(`  ${g}:${n}`);
}
console.log();
