#!/usr/bin/env node
/**
 * Build the unminified, import-free CSS distribution.
 *
 * Relative asset URLs are rebased from their source file to kit/dist, so the
 * self-hosted fonts keep working after imports are flattened. Form tokens are
 * wrapped in wx.form, the last declared cascade layer.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const kit = join(root, "kit");
const out = join(kit, "dist");
const importPattern = /@import\s+["']([^"']+)["'](?:\s+layer\(([^)]+)\))?\s*;/g;

function slash(value) {
  return value.split(sep).join("/");
}

function rebaseUrls(css, sourceFile) {
  return css.replace(/url\((['"]?)(?!data:|https?:|\/|#)([^)'"\s]+)\1\)/g, (_match, quote, value) => {
    const absolute = resolve(dirname(sourceFile), value);
    const rebased = slash(relative(out, absolute));
    return `url(${quote}${rebased}${quote})`;
  });
}

function flatten(file, stack = []) {
  const absolute = resolve(file);
  if (stack.includes(absolute)) {
    throw new Error(`CSS import cycle: ${stack.concat(absolute).map((p) => relative(root, p)).join(" -> ")}`);
  }
  // Rebase each source file before expanding imports. Rebasing the fully
  // expanded parent would rewrite URLs from child files a second time.
  const source = rebaseUrls(readFileSync(absolute, "utf8"), absolute);
  const nextStack = stack.concat(absolute);
  const expanded = source.replace(importPattern, (_match, request, layer) => {
    const imported = flatten(resolve(dirname(absolute), request), nextStack);
    const body = `/* source: ${slash(relative(root, resolve(dirname(absolute), request)))} */\n${imported}`;
    return layer ? `@layer ${layer.trim()} {\n${body}\n}` : body;
  });
  return expanded.trim();
}

const banner = (name) => `/* 文心 · 万形 ${name}\n   Generated by scripts/build-css.mjs. Unminified by decision. */\n`;
const base = flatten(join(kit, "index.css"));

mkdirSync(out, { recursive: true });
writeFileSync(join(out, "wenxin.css"), `${banner("complete kit")}${base}\n`);

/* Per-medium bundles were removed: nine files carried 145 lines of real
   difference across 30,000 lines, because each was the complete kit plus a
   handful of tokens. A consumer loads wenxin.css and adds the one
   kit/tokens/forms/ file they need. */
console.log("✓ wenxin.css → kit/dist/ (unminified, import-free)");
